// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {context} from '../models';

export function Configure(arg1:Record<string, any>):Promise<void>;

export function ConfirmClose():Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DismissFirstRun():Promise<void>;

export function DuplicateModel(arg1:string,arg2:string):Promise<void>;

export function GenerateAPIKey():Promise<string>;

export function GetAPIKey():Promise<string>;

export function GetCapabilities(arg1:string):Promise<Record<string, boolean>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetSnapshot():Promise<core.Snapshot>;

export function IsFirstRun():Promise<boolean>;

export function IsRunning():Promise<boolean>;

export function PortInUse(arg1:number):Promise<boolean>;

export function Refresh():Promise<void>;

export function ResetFirstRun():Promise<void>;

export function RestartServer():Promise<void>;

export function RestoreDefaults():Promise<void>;

export function SaveLogging(arg1:boolean,arg2:number,arg3:boolean):Promise<void>;

export function SaveModel(arg1:core.ModelInput):Promise<void>;

export function SaveProvider(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SetAPIKeyEnabled(arg1:boolean):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetGlobalConcurrency(arg1:number):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function TestModel(arg1:string):Promise<core.TestResult>;

export function TestProvider(arg1:string):Promise<core.TestResult>;

export function TestProviderCancelable(arg1:context.Context,arg2:string):Promise<core.TestResult>;
